### ISSUE TITLE
Alphabetization of terms in categories

### ISSUE THREAD

**Issue by clendara1** [biosemantics/etc-site#269]
For large datasets it would be useful to have the terms alphabetized, including in the "one category" view.  The reason for this is that there are some cases where a word has been misspelled and it cannot be corrected because the right spelled term already exists.  The only alternative is to synonymize the misspelled word with the correctly spelled word.  
In the following example the term "awns" can be found in the center of the screen, between midstrip and leaf axil.  Check the position of placentation and placentatian; and inflorescent and inflorescences. 
![alphabetization](https://cloud.githubusercontent.com/assets/8581741/8292545/420fc996-18fe-11e5-9b16-22c48cffc673.JPG)
In the last two cases it is possible to identify the synonyms because they are visible, but in the case of terms that do not appear in the same screen is rather difficult to navigate to them.  Having them in alphabetical order will be very useful.

**Comment by rodenhausen** [comment]
(1) Should we order categories by alphabet too or only the terms inside a category?
(2) Should we order the terms every time a term is inserted or only when the dataset is loaded (It could become an efficiency problem in the single category view, because the browser has to do more rendering work for reordering when term is inserted; Not so much an issue for the "All categories view")
(3) We have to order the model the client holds when a new term is inserted. This will make sure the terms are loaded in alphabetical order when the user switches from category to category in single category view and does not cause additional rendering (we have to render either way)

**Comment by rodenhausen** [comment]
(1) sort labels and terms. 

(2) Allow user to trigger sort terms in category with the settings button in the category box, or upon a right click context menu action. Similarly for trigger of sort labels.
We are not going to sort anything automatically (only when the dataset is initially loaded).
Do this similarly for both "all category" and "single category" view.

(3) Obsolete, we let the user trigger the sort when he wants (he may prefer unsorted to find terms he inserted easier)
