### ISSUE TITLE
TextCapture:Term Review: import categorizations

### ISSUE THREAD

**Issue by hongcui** [biosemantics/etc-site#487]
Two issues:
Starting with 'armed' and 'angled' in architecture, I was able to import 'armed' without a categorization, ",armed", which result in
![image](https://cloud.githubusercontent.com/assets/831423/14621766/f4dee1c0-0579-11e6-9351-11aa41149301.png)

What I would have expected is:
1. 'armed' be put in the left panel (to be categorized)
2. no import, because 'armed' is currently categorized as architure. 
or
3. no import, because category info was not given

I prefer solution 1. 

Also I was not be able to import synonyms at all.

**Comment by rodenhausen** [comment]
I will implement 2. because it would go against the current logic of our implementation overall. A term is either uncategorized (left panel) or categorized (in one or multiple categories on the right panel).

For a scenario, where a term does not exist in the dataset and the same format on import is used I will add it to the left panel.
