### ISSUE TITLE
[Ontology Building]Prompt 'out of sync' when add synonym pattern

### ISSUE THREAD

**Issue by CathyYujie** [biosemantics/etc-site#615]
![image](https://cloud.githubusercontent.com/assets/22200814/22381764/24d79170-e480-11e6-8841-313deb2959ea.png)

![image](https://cloud.githubusercontent.com/assets/22200814/22381752/14bdbecc-e480-11e6-95ea-ad096371b276.png)

![image](https://cloud.githubusercontent.com/assets/22200814/22381806/49b7d676-e480-11e6-90ee-69b76f57b409.png)
and the synonym relation between "strong armed" and "strong-armed" will disappear after refresh the page

**Comment by CathyYujie** [comment]
When choose two same options at one time and click ok, it will still give the prompt 'out of sync' and this relation will be added into system successfully.
![image](https://cloud.githubusercontent.com/assets/22200814/23088061/53e856c2-f536-11e6-8264-53640649e61f.png)

If you choose one of them, it goes well.

Advice:
Just keep one option for this relation in the pattern window.
It is a bit hard to understand why there are two options for recommending  the same relation in the pattern pop-up window. Meanwhile, it will not raise the wrong prompt.

-----
tips: I have refreshed my browser before test.

**Comment by danveno** [comment]
Through multiple attempts, I tried to find the reason why it gives "out of sync" alerts. 
First, it looks like that it's not an error but an alert. But the console does report some errors saying some term is not attached to the Synonym-root. It seems that the problem is about synonym patterns. If the preferred term is not added first, the error will come. In GWT client, the preferred term has been checked and added if not existed.  But I guess adding preferred term in server is not always ahead of adding synonyms due to network problem and Javascript runtime environment.
